version: '3'

services:
    ctf:
        build: ./
        restart: always
        ports:
            - "30001:30001"
        expose:
            - "30001"
        expose:
            - "30001"
        read_only: true
